### ISSUE TITLE
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### ISSUE THREAD

**Issue by rabiaedayilmaz** [MedicineToken/Medical-SAM2#37]
While running 2D REFUGE data example training&validation command, which is `python train_2d.py -net sam2 -exp_name REFUGE_MedSAM2 -vis 1 -sam_ckpt ./checkpoints/sam2_hiera_small.pt -sam_config sam2_hiera_s -image_size 1024 -out_size 1024 -b 4 -val_freq 1 -dataset REFUGE -data_path ./data/REFUGE`, an error occurs.

Full Error Log:
```
/content/Medical-SAM2/sam2_train/modeling/sam/transformer.py:22: UserWarning: Flash Attention is disabled as it requires a GPU with Ampere (8.0) CUDA capability.
  OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()
INFO:root:Namespace(net='sam2', encoder='vit_b', exp_name='REFUGE_MedSAM2', vis=True, train_vis=False, prompt='bbox', prompt_freq=2, pretrain=None, val_freq=1, gpu=True, gpu_device=0, image_size=1024, out_size=1024, distributed='none', dataset='REFUGE', sam_ckpt='./checkpoints/sam2_hiera_small.pt', sam_config='sam2_hiera_s', video_length=2, b=4, lr=0.0001, weights=0, multimask_output=1, memory_bank_size=16, data_path='./data/REFUGE', path_helper={'prefix': 'logs/REFUGE_MedSAM2_2024_09_07_12_17_24', 'ckpt_path': 'logs/REFUGE_MedSAM2_2024_09_07_12_17_24/Model', 'log_path': 'logs/REFUGE_MedSAM2_2024_09_07_12_17_24/Log', 'sample_path': 'logs/REFUGE_MedSAM2_2024_09_07_12_17_24/Samples'})
Namespace(net='sam2', encoder='vit_b', exp_name='REFUGE_MedSAM2', vis=True, train_vis=False, prompt='bbox', prompt_freq=2, pretrain=None, val_freq=1, gpu=True, gpu_device=0, image_size=1024, out_size=1024, distributed='none', dataset='REFUGE', sam_ckpt='./checkpoints/sam2_hiera_small.pt', sam_config='sam2_hiera_s', video_length=2, b=4, lr=0.0001, weights=0, multimask_output=1, memory_bank_size=16, data_path='./data/REFUGE', path_helper={'prefix': 'logs/REFUGE_MedSAM2_2024_09_07_12_17_24', 'ckpt_path': 'logs/REFUGE_MedSAM2_2024_09_07_12_17_24/Model', 'log_path': 'logs/REFUGE_MedSAM2_2024_09_07_12_17_24/Log', 'sample_path': 'logs/REFUGE_MedSAM2_2024_09_07_12_17_24/Samples'})
Traceback (most recent call last):
  File "/content/Medical-SAM2/train_2d.py", line 124, in <module>
    main()
  File "/content/Medical-SAM2/train_2d.py", line 97, in main
    tol, (eiou, edice) = function.validation_sam(args, nice_test_loader, epoch, net, writer)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/Medical-SAM2/func_2d/function.py", line 335, in validation_sam
    vision_feats_temp = vision_feats[-1].permute(1, 0, 2).view(B, -1, 64, 64) 
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
ERROR conda.cli.main_run:execute(124): conda run bash -c python train_2d.py -net sam2 -exp_name REFUGE_MedSAM2 -vis 1 -sam_ckpt ./checkpoints/sam2_hiera_small.pt -sam_config sam2_hiera_s -image_size 1024 -out_size 1024 -b 4 -val_freq 1 -dataset REFUGE -data_path ./data/REFUGE failed. (See above for error)
```

System Info:
```
Python version: 3.10.12 
conda 23.11.0
Ubuntu 22.04.3
```

The mentioned error was fixed in this PR: https://github.com/MedicineToken/Medical-SAM2/pull/36

**Comment by jiayuanz3** [comment]
thanks for your contribution and I've merged it in!
