### ISSUE TITLE
Cannot run 3d training

### ISSUE THREAD

**Issue by Youzhuqinghuan** [MedicineToken/Medical-SAM2#5]
I encountered an error while trying to run training on the BTCV dataset you provided. The error message was: "ImportError: cannot import name '_C' from 'sam2_train'." The full error message is:

Traceback (most recent call last):
  File "Medical-SAM2/train_3d.py", line 112, in <module>
    main()
  File "Medical-SAM2/train_3d.py", line 95, in main
    loss, prompt_loss, non_prompt_loss = function.train_sam(args, net, optimizer1, optimizer2, nice_train_loader, epoch)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Medical-SAM2/func_3d/function.py", line 114, in train_sam
    _, _, _ = net.train_add_new_bbox(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "Medical-SAM2/sam2_train/sam2_video_predictor.py", line 439, in train_add_new_bbox
    out_frame_idx, out_obj_ids, out_mask_logits = self.train_add_new_points(
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Medical-SAM2/sam2_train/sam2_video_predictor.py", line 523, in train_add_new_points
    current_out, _ = self._run_single_frame_inference(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Medical-SAM2/sam2_train/sam2_video_predictor.py", line 1351, in _run_single_frame_inference
    pred_masks_gpu = fill_holes_in_mask_scores(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Medical-SAM2/sam2_train/utils/misc.py", line 254, in fill_holes_in_mask_scores
    labels, areas = get_connected_components(mask <= 0)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Medical-SAM2/sam2_train/utils/misc.py", line 61, in get_connected_components
    from sam2_train import _C
ImportError: cannot import name '_C' from 'sam2_train' (Medical-SAM2/sam2_train/__init__.py)

I’m having trouble understanding this error and would appreciate any help you can offer. Thank you so much!

**Comment by YunliQi** [comment]
Could you please check whether the file _C.so is in the path `Medical-SAM2/sam_train/`?

**Comment by Youzhuqinghuan** [comment]
It seems that there’s no `_C.so` file in the `Medical-SAM2/sam_train/` directory. How can I obtain it? Thank you so much!

**Comment by YunliQi** [comment]
You can try to download it from the GitHub repo, it is in the path `sam2_train/_C.so`

**Comment by Youzhuqinghuan** [comment]
I found the issue. The file is excluded by `.gitignore`, so I can obtain it when I clone the repository. Thank you for helping with my stupid question!XD
