### ISSUE TITLE
train_3d.py: cannot import name '_C' from 'sam2_train'

### ISSUE THREAD

**Issue by godspeedlucip** [MedicineToken/Medical-SAM2#63]
I have met the same question, and I have confirmed that the `_C.so` file is in the `Medical-SAM2/sam_train/` dirrectory. Could anyone know how to solve it?
Hear is my environment:
python: 3.12.7
CUDA: V11.8.89
torch: 2.3.1+cu118
gpu: NVIDIA GeForce RTX 3060

Here is my log:

```
Traceback (most recent call last):
  File "E:\desktop\MedSAM2\Medical-SAM2-main\train_3d.py", line 114, in <module>
    main()
  File "E:\desktop\MedSAM2\Medical-SAM2-main\train_3d.py", line 97, in main
    loss, prompt_loss, non_prompt_loss = function.train_sam(args, net, optimizer1, optimizer2, nice_train_loader, epoch)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\desktop\MedSAM2\Medical-SAM2-main\func_3d\function.py", line 114, in train_sam
    _, _, _ = net.train_add_new_bbox(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\desktop\MedSAM2\Medical-SAM2-main\sam2_train\sam2_video_predictor.py", line 439, in train_add_new_bbox
    out_frame_idx, out_obj_ids, out_mask_logits = self.train_add_new_points(
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\desktop\MedSAM2\Medical-SAM2-main\sam2_train\sam2_video_predictor.py", line 523, in train_add_new_points
    current_out, _ = self._run_single_frame_inference(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\desktop\MedSAM2\Medical-SAM2-main\sam2_train\sam2_video_predictor.py", line 1351, in _run_single_frame_inference
    pred_masks_gpu = fill_holes_in_mask_scores(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\desktop\MedSAM2\Medical-SAM2-main\sam2_train\utils\misc.py", line 259, in fill_holes_in_mask_scores
    labels, areas = get_connected_components(mask <= 0)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\desktop\MedSAM2\Medical-SAM2-main\sam2_train\utils\misc.py", line 66, in get_connected_components
    from sam2_train import _C
ImportError: cannot import name '_C' from 'sam2_train' (E:\desktop\MedSAM2\Medical-SAM2-main\sam2_train\__init__.py)
```

below is my directory：
![Uploading image.png…]()

**Comment by DemerzelWang** [comment]
same problem

**Comment by jiayuanz3** [comment]
I think you have already solved the problem based on https://github.com/MedicineToken/Medical-SAM2/issues/26.
